name: tadrep
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython>=1.78
  - xopen>=1.1.0
  - blast>=2.12.0
  - matplotlib>=1.4
  - pip=21.0.1
  - pip:
      - attrs==20.3.0
      - dnaplotlib==1.0