name: tadrep
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython>=1.78
  - xopen>=1.5.0
  - pyrodigal>=2.1.0
  - blast>=2.12.0
  - cd-hit>=4.8.1
  - matplotlib>=3.7
  - pygenomeviz>=0.4